### ISSUE TITLE
Launch business site

### ISSUE THREAD

**Issue by celineaudinsap** [sap-tutorials/sap-build-process-automation#200]
Impacted tutorial: https://developers.sap.com/tutorials/spa-run-business-process-business-site.html

To launch a business site you need to create a site first:
https://help.sap.com/docs/build-work-zone-standard-edition/sap-build-work-zone-standard-edition/create-site

Assign roles to your site:
https://help.sap.com/docs/build-work-zone-standard-edition/sap-build-work-zone-standard-edition/assign-roles-to-your-site-7afe6706346844d9b9879997a0b9f350-109?q=assign%20role

In addition, for the user to see the content assigned to the site, the user must be assigned to the same role of the site.

Link to ticket: 
https://itsm.services.sap/now/cwf/agent/record/x_sapda_devinc_development_incident/45dcd4aec3948e942f44578f0501318a

**Comment by chaitanya-priya-puvvada** [comment]
Hi @celineaudinsap :
 Configure  SAP Build Workzone tutorial is used as reference in several tutorials, since creating a business site is common, can we remove the step of creating business site from the tutorial https://developers.sap.com/tutorials/spa-run-business-process-business-site.html and add it in https://developers.sap.com/tutorials/spa-configure-workzone.html .

**Comment by celineaudinsap** [comment]
updates done
