### ISSUE TITLE
Create Destination to Trigger Process from any Service

### ISSUE THREAD

**Issue by jsunil0101** [sap-tutorials/sap-build-process-automation#46]
Tutorials: https://developers.sap.com/tutorials/spa-create-service-instance-destination.html
--------------------------

Prerequisites
 is Free Tier service plans, you can't create instance from free plan, you need standard plan.

**Comment by ASRHARDING** [comment]
I believe I have the same problem as jsunil0101 above, after using the “Set up account for SAP Build Process Automation (Free)” booster to subscribe to SAP Build Process Automation I am unable to then create a service Instance for SAP Build Process Automation. See the attached screenshot below.

The Global service assignments in my account includes multiple plans for “SAP Build Process Automation”: advanced-user; automation-attended; automation-unattended; free (Application); standard (Application); standard-user. In addition, there is a standard plan for “SAP Build Process Automation Service”. 

Since the “Set up account for SAP Build Process Automation (Free)” only adds the “free (Application)” plan it would appear you need to assign the “standard (Application)”, “standard-user” and/or the “SAP Build Process Automation Service” standard plan to be able to create a service instance.

Checking the SAP Build Process Automation pricing in the Service Catalogue:
https://discovery-center.cloud.sap/serviceCatalog/sap-build-process-automation?region=all&tab=service_plan&commercialModel=payg
It would appear that to perform this tutorial one would need a standard user service plan, that would incur charging as per the Standard User description in the pricing guide (link above).

I note that the steps for Standard plan appears to use a different booster “Set up account for SAP Build Process Automation” without the word “Free” in the title (see https://help.sap.com/docs/PROCESS_AUTOMATION/a331c4ef0a9d48a89c779fd449c022e7/089a5d6f47b344e8b370460098980b9b.html)

It appears that to create a service instance as part of this tutorial you should use “SAP Build Process Automation” booster, without “(Free)” in the title, to setup the standard plan, and then you can create a service instance for SAP Build Process Automation as described in this tutorial. In the process you would incur charges as per a Standard User.
 
Can you please confirm the above is correct, and if so, amend the tutorial prerequisites to state that you will need at least one chargeable Standard User license to perform the tutorial.

![Create SAP Build Process Automation Service Insntance](https://user-images.githubusercontent.com/57531943/221629789-aef1d36e-cb61-4193-a535-a242f8917ddd.png)
